hmLoadTopic({
hmKeywords:"",
hmTitle:"Expert settings",
hmDescription:"Expert settings  Expert settings are for advanced users. Change them only at the direction of the technical support or developers.  Bluetooth scan time - the maximum time durin",
hmPrevLink:"settings.html",
hmNextLink:"device_settings.html",
hmParentLink:"settings.html",
hmBreadCrumbs:"<a href=\"settings.html\">Application settings<\/a>",
hmTitlePath:"Application settings > Expert settings",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Expert settings<\/span><\/h1>\n\r",
hmBody:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Expert settings<\/span><\/h1>\n\r<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">&nbsp;<\/span><\/h1>\n\r<p class=\"p_Normal\"><span style=\"color: #c0504d;\">Expert settings are for advanced users. Change them only at the direction of the technical support or developers.<\/span><\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\"><span style=\"font-weight: bold;\">Bluetooth scan time<\/span> - the maximum time during which the application waits from the system for a response to a request to build a list of available Bluetooth devices. By default, it is 20 seconds. Under normal conditions, when the device is working properly, is near the phone and there is no interference, scanning for Bluetooth devices is much faster and there is no need to adjust the scan time.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\"><span style=\"font-weight: bold;\">Connection timeout:<\/span> The time during which the application waits for a connection to the device. If the connection is unstable, you can try to increase this time.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\"><span style=\"font-weight: bold;\">Location request rate:<\/span> The desired interval at which the application receives location information from the system. This time is an approximate one and the system can inform the application about the change in location either more often or less often than the specified interval. Increasing the interval saves battery life on your smartphone, decreasing the interval may make location determination more frequent (which can be important when traveling at high speeds), but it will drain the battery faster.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\"><span style=\"font-weight: bold;\">Use legacy Google Maps renderer:<\/span> Google announced the availability of a new, improved map renderer. If you disable the &quot;Use legacy Google Maps renderer&quot; option, then<\/p>\n\r<p class=\"p_Normal\">the RadiaCode application requests the use of a new renderer. However, when using the new renderer, map rendering is often noticeably slower. <span style=\"font-style: italic;\">The effect of changing the value of this option appears only after restarting the application.<\/span><\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\"><span style=\"font-weight: bold;\">“Debug” group settings<\/span> are associated with debug information that is written to the application log file in diagnostic mode. The developers may ask you to enable this or that option in order to better understand the problem that has arisen. All of these options are disabled by default. enabling them significantly increases the size of the log file and can affect application performance. After enabling debug options, you need to restart the application.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r"
})
