hmLoadTopic({
hmKeywords:"",
hmTitle:"Displaying isotope information",
hmDescription:"When you tap the graph and move your finger across the screen, the application header displays information about the radioactive isotope, the energy of which corresponds to the...",
hmPrevLink:"background.html",
hmNextLink:"spectrum_settings.html",
hmParentLink:"spectrum.html",
hmBreadCrumbs:"<a href=\"spectrum.html\">Spectrum<\/a>",
hmTitlePath:"Spectrum > Displaying isotope information",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Displaying isotope information<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\">When you tap the graph and move your finger across the screen, the application header displays information about the radioactive isotope, the energy of which corresponds to the cursor position:<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\"><img alt=\"isotope_title\" style=\"margin:0;width:22.5000rem;height:3.2500rem;border:none\" src=\".\/images\/isotope_title.png\"\/><\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">The name of the isotope, the corresponding energy is displayed, in square brackets - the energy corresponding to the cursor line on the spectrum graph. The name of the decay chain for the isotope is displayed below.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\"><span style=\"font-weight: bold;\">To see examples of spectra of common isotopes, tap <a href=\"https:\/\/scan-electronics.com\/en\/isotopes\" target=\"_blank\" class=\"weblink\">here<\/a>.<\/span><\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">In case the option &quot;Display gamma line position&quot; is enabled:<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">The pink line marks the position of the isotope energy line. If the isotope has accompanying lines, then they are displayed in turquoise (<a href=\"spectrum.html\" class=\"topiclink\">see the figure in the “Spectrum” topic<\/a>). The dotted lines correspond to the X-ray lines.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">If there are several isotopes with close energies, then information about that isotope is displayed, the energy line of which is closest to the value of the energy corresponding to the cursor.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">If the &quot;Display gamma lines intensity&quot; or &quot;Draw markers on intensity lines&quot; option is enabled, red lines\/markers corresponding to the intensity of gamma radiation lines, relative to the activity of the parent nuclide, are drawn over or instead of turquoise isotope lines.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_SubTitle\"><span class=\"f_SubTitle\">&nbsp;<\/span><\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r"
})
