hmLoadTopic({
hmKeywords:"",
hmTitle:"Spectrum histogram",
hmDescription:"The menu command \"Spectrum Histogram\" in the tab \"Spectrogram\" opens the panel in which the spectrum corresponding to the interval selected in the spectrogram is displayed:",
hmPrevLink:"spectrogram.html",
hmNextLink:"activity.html",
hmParentLink:"spectrogram.html",
hmBreadCrumbs:"<a href=\"spectrogram.html\">Spectrogram<\/a>",
hmTitlePath:"Spectrogram > Spectrum histogram",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Spectrum histogram<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\">The menu command &quot;Spectrum Histogram&quot; in the tab &quot;Spectrogram&quot; opens the panel in which the spectrum corresponding to the interval selected in the spectrogram is displayed:<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\"><img alt=\"SpgSpectrum\" style=\"margin:0;width:22.5000rem;height:29.6250rem;border:none\" src=\".\/images\/spgspectrum.png\"\/><\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">The interval is selected by dragging the triangles (markers). The scale of the spectrum (linear or logarithmic) corresponds to the scale selected for the spectrogram.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">If the marker position is outside the spectrogram area displayed on the screen, the background of the marker will be semi-transparent.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">A long touch of the marker sets its position to the corresponding extreme value. If, for example, you perform a long tap on both markers, the spectrum will be displayed for the entire spectrogram.<\/p>\n\r<p class=\"p_Normal\">&nbsp;<\/p>\n\r<p class=\"p_Normal\">If during the recording of the spectrogram the corresponding marker is set to the extreme value, which corresponds to the most recent data, then when new data comes from the device, the marker will automatically move to the new extreme position, i.e. as if it &quot;sticks&quot; to the boundary. The behavior of the second marker in such a situation depends on the setting &quot;Do not shift the initial boundary of the spectrum histogram range in the automatic end boundary shift mode&quot;. If this setting is enabled (default), the second marker stays where it was and the spectrum interval increases as new data is received from the device. If this setting is off, the second marker is moved so that the interval between the markers remains constant and the spectrum is displayed over the selected fixed interval.<\/p>\n\r"
})
