pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./activity.htm","Activity","The &#8220;Activity&#8221; tab is designed to determine the absolute and specific activity of the Cs-137 isotope in various loose and watery materials (primar...",""],
["./background.htm","Spectrum &#62; Background Usage","In the application RadiaCode it is possible to display on the graph not only the spectrum of accumulated emission, but also to compare the spectru...",""],
["./calibrate.htm","Spectrum &#62; Calibrating the energy scale of the device","Calibrating the energy scale of the spectrum is necessary to accurately determine the energy of the gamma lines of the spectrum by the channel num...",""],
["./camera.htm","Camera","The RadiaCode application provides photo-related features:",""],
["./camera_settings.htm","Camera &#62; Camera settings","Camera settings are called up by pressing the  button from the camera mode. ",""],
["./connection.htm","If the application cannot find the device...","There may be situations, when the application cannot connect with the device via Bluetooth or the connection with the device is unstable. In this ...",""],
["./container.htm","Activity &#62; Measurement of sample activity in a container","Measurement procedure  IMPORTANT: To determine the activity of loose and watery materials, it is necessary to give them a standard shape by p...",""],
["./devices.htm","Devices","Device selection is available through the navigation menu (icon in the upper left corner of the screen). The device selection page is displayed:",""],
["./device_settings.htm","Device Settings","If the device is connected, then the device settings are available through the navigation menu (pictogram in the upper left corner of the screen)....",""],
["./expert_settings.htm","Application settings &#62; Expert settings","Expert settings  Expert settings are for advanced users. Change them only at the direction of the technical support or developers.  Blue...",""],
["./export_import.htm","Export and import","The RadiaCode application implements the export and import of spectra, spectrograms and tracks. Export in the Android system is traditionally desi...",""],
["./feedback.htm","Feedback","A form opens where you can send a letter with wishes to the developers or report bugs in the application. You need to enter your name and email, t...",""],
["./folders.htm","Folders in the libraries","In the libraries of spectra, spectrograms, tracks and device profiles, you can place the contents in folders, just like in the file system. No fol...",""],
["./graphs.htm","Main Screen &#62; Graph displaying","The count rate and dose rate graphs display data and are operated in the same way.",""],
["./graph_settings.htm","Main Screen &#62; Graph settings","Graph settings are accessed with the button . The count rate and dose rate graphs have the same settings, individual for each graph.",""],
["./intro.htm","Introduction","This section contains introductory information about the application. RadiaCode  and its joint use with the device  RadiaCode-10X.",""],
["./isotopes.htm","Spectrum &#62; Displaying isotope information","When you tap the graph and move your finger across the screen, the application header displays information about the radioactive isotope, the ener...",""],
["./iso_hardness.htm","Main Screen &#62; Pseudo-determination of isotopes by radiation hardness","The radiation hardness graph makes it possible at any time to estimate which energies predominate in the gamma-ray spectrum (low, medium, high). T...",""],
["./libs.htm","Spectrum, spectrogram and track libraries","The spectra, spectrograms and tracks storages are called libraries and are stored in the application database. We will call a spectrum, spectrogra...",""],
["./log.htm","Log","This page displays the current and past measurement data in a table. As new meaningful data becomes available, it is added to the log.",""],
["./main_screen.htm","Main Screen","Screen fragments:   The application name, its version and the version of the device firmware, if it is connected. If an app update is availab...",""],
["./map.htm","Map and tracks","Application RadiaCode equipped with functions of displaying the emission situation on a map in real time, as well as functions of recording routes...",""],
["./map_settings.htm","Map and tracks &#62; Map settings","To open the map settings, tap  at the top left of the screen.",""],
["./point_source.htm","Activity &#62; Point source activity measurement","Measurement procedure  1) Charge the device to at least 50% capacity and using the &#8220;Spectrum&#8221; mode generate a background spectrum set. When o...",""],
["./precaution.htm","Introduction &#62; Safety engineering &#62; Precautionary measures","Read the operating instructions before using the device.",""],
["./pseudo_tracks.htm","Map and tracks &#62; Pseudo tracks","A pseudo track is a track generated by the application based on the dose rate data that was written to the database when the option is enabled &#8220;Sa...",""],
["./quickstart.htm","Quick start","Connecting the application to the device RadiaCode",""],
["./safety_regulations.htm","Introduction &#62; Safety engineering","Read the instructions before using the device.  Safety warning Precautionary measures",""],
["./search.htm","Search","The \"Search\" mode is designed to analyze the operational (\"raw\") data of the device and search for a source of radiation or he...",""],
["./search_settings.htm","\"Search\" mode settings","\"Search\" mode settings are accessed with the button . The count rate and dose rate graphs have the same settings, individual for each gr...",""],
["./security_warning.htm","Introduction &#62; Safety engineering &#62; Safety warning","Store the device out of the reach of children and pets. To avoid accidents, keep the device and accessories out of the reach of children and pets.",""],
["./settings.htm","Application settings","Application settings are available through the navigation menu (pictogram in the upper left corner of the screen). ",""],
["./share.htm","Spectrum &#62; Export and import of spectra","Spectra are exported with the command &#8220;Share&#8221;, which is called through the dropdown menus in the &#8220;Spectrum&#8221; and &#8220;View&#8221; tabs, as well as the window...",""],
["./sp10bit.htm","Spectrum &#62; 1024 spectrum channels instead of 256","Device firmware version 4+ supports 1024-channel spectra. Earlier firmware versions supported 256-channel spectra.",""],
["./spectrogram.htm","Spectrogram","A spectrogram is a visual representation of the energy spectrum of photon (gamma and X-ray) radiation varying with time.",""],
["./spectrum.htm","Spectrum","This window displays the energy spectrum of the photon (gamma and X-ray) radiation, typed by the device over a certain period of time. When you co...",""],
["./spectrum_settings.htm","Spectrum &#62; Spectrum settings","The spectrum settings are called by the  button on the \"Spectrum\" and \"View\" tabs. The spectrum settings are the same for...",""],
["./spectrum_view.htm","Spectrum &#62; View tab","The &#8220;View&#8221; tab is intended for static viewing of spectra from spectra libraries. The functionality of the tab and control is the same as on the ma...",""],
["./spg_spectrum_win.htm","Spectrogram &#62; Spectrum histogram","The menu command \"Spectrum Histogram\" in the tab \"Spectrogram\" opens the panel in which the spectrum corresponding to the inte...",""],
["./widgets.htm","App widgets","If you don&#39;t know what a widget is and how to put it on your smartphone&#39;s desktop, look on the Internet for help.",""]];
